let products=[
    {
       id: 1001,
       Subject: "Cricket",
       Location: "Dubai",
       Price: 100,
       Availability: 10,
       image: "images/—Pngtree—colorful cricket batsman hitting_16078173.png",
       rating: 5,
   },
   {
       id: 1002,
       Subject: "Football",
       Location: "Sharjah",
       Price: 90,
       Availability: 10,
       image: "images/—Pngtree—football player with the ball_5819342.png",
       rating: 3.5,
   },
   {
       id: 1003,
       Subject: "Tennis",
       Location: "Ajman",
       Price: 95,
       Availability: 10,
       image: "images/tennis.png",
       rating: 3,
   },
   {
       id: 1004,
       Subject: "Judo",
       Location: "Ajman",
       Price: 85,
       Availability: 10,
       image: "images/Judo.png",
       rating: 4,
   },
   {
       id: 1005,
       Subject: "Badminton",
       Location: "Ajman",
       Price: 90,
       Availability: 10,
       image: "images/badminton.png",
       rating: 3,
   },
   {
       id: 1006,
       Subject: "Swimming",
       Location: "Sharjah",
       Price: 70,
       Availability: 10,
       image: "images/Swimming.png",
       rating: 4,
   },
   {
       id: 1007,
       Subject: "Basketball",
       Location: "Dubai",
       Price: 100,
       Availability: 10,
       image: "images/Basketball.png",
       rating: 5,
   },
   {
       id: 1008,
       Subject: "Abacus",
       Location: "Dubai",
       Price: 110,
       Availability: 10,
       image: "images/Abacus.png",
       rating: 4,
   },
   {
       id: 1009,
       Subject: "Languages",
       Location: "Dubai",
       Price: 80,
       Availability: 10,
       image: "images/Languages.png",
       rating: 4,
   },
   {
       id: 1010,
       Subject: "Chess",
       Location: "Ajman",
       Price: 90,
       Availability: 10,
       image: "images/Chess.png",
       rating: 4,
   },
]